version: "1"

services:
  mongo:
    container_name: mongo-db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/app/src
      - ./public:/usr/app/public
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo-db:27017/my-db
      - JWT_SECRET=jwttoken
      - ADMIN_EMAIL=admin@waltercode.com
      - ADMIN_PASSWORD=admin123
      - START_DATE=1/1/2023
      - END_DATE=12/31/2023
    ports:
      - 3000:3000
    depends_on:
      - mongo
volumes:
  mongo-data:
    driver: local
